import type { Metadata } from "next"

export const SITE_URL = "https://tapagopay.net"
export const SITE_NAME = "Tapago"

// Generated by app/opengraph-image.tsx. Pages that set their own openGraph must re-declare it.
const OG_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: "Tapago — Pagos internacionales para empresas" }

/**
 * Per-page metadata. Next merges `openGraph`/`twitter` shallowly, so every page sets the full objects
 * to keep siteName/locale/image and its own URL.
 */
export function pageMetadata({ title, description, path }: { title: string; description: string; path: string }): Metadata {
  const fullTitle = `${title} — ${SITE_NAME}`
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: { title: fullTitle, description, url: path, siteName: SITE_NAME, locale: "es_AR", type: "website", images: [OG_IMAGE] },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [OG_IMAGE] },
  }
}
